language: go

script:
 - go test -v ./...

before-deploy:
 - GOOS=linux GOARCH=amd64 go build -o csvmask-$TRAVIS_TAG-linux-amd64
 - GOOS=linux GOARCH=arm go build -o csvmask-$TRAVIS_TAG-linux-arm
 - GOOS=darwin GOARCH=amd64 go build -o csvmask-$TRAVIS_TAG-darwin-amd64
 - GOOS=windows GOARCH=amd64 go build -o csvmask-$TRAVIS_TAG.exe

 deploy:
  skip_cleanup: true

deploy:
  provider: releases
  api_key: "GITHUB OAUTH TOKEN"
  file: "FILE TO UPLOAD"
  skip_cleanup: true
  on:
    tags: true

after_deploy:
- go clean