language: go

jobs:
  include:
  - stage: test
    script: go test -v ./...
  - stage: build
    script: mkdir release
    script: "GOOS=linux GOARCH=amd64 go build -o csvmask-$TRAVIS_TAG-linux-amd64"
    script: "GOOS=linux GOARCH=arm go build -o csvmask-$TRAVIS_TAG-linux-arm"
    script: "GOOS=darwin GOARCH=amd64 go build -o csvmask-$TRAVIS_TAG-darwin-amd64"
    script: "GOOS=windows GOARCH=amd64 go build -o csvmask-$TRAVIS_TAG.exe"
  - stage: deploy
    script: echo "Deploying to GitHub releases ..."
      deploy:
        provider: releases
        api_key: $GITHUB_OAUTH_TOKEN
        file:
        - "csvmask-$TRAVIS_TAG-linux-amd64"
        - "csvmask-$TRAVIS_TAG-linux-arm"
        - "csvmask-$TRAVIS_TAG-darwin-amd64"
        - "csvmask-$TRAVIS_TAG.exe"
        skip_cleanup: true
        on:
          tags: true
    - stage: clean-up
      script: go clean