language: go

script: go test -v ./...

before_deploy:
  - GOOS=linux GOARCH=amd64 go build -o csvmask-$TRAVIS_TAG-linux-amd64
  - GOOS=linux GOARCH=arm go build -o csvmask-$TRAVIS_TAG-linux-arm
  - GOOS=darwin GOARCH=amd64 go build -o csvmask-$TRAVIS_TAG-darwin-amd64
  - GOOS=windows GOARCH=amd64 go build -o csvmask-$TRAVIS_TAG.exe

deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file:
    - csvmask-$TRAVIS_TAG-linux-amd64
    - csvmask-$TRAVIS_TAG-linux-arm
    - csvmask-$TRAVIS_TAG-darwin-amd64
    - csvmask-$TRAVIS_TAG.exe
  skip_cleanup: true
  on:
    tags: true

after_deploy:
  - go clean