language: go

jobs:
  include:
    - stage: test
      script: echo "stage 1" > test.txt
    - stage: test
      script: cat test
      script: echo "stage 2" >> test.txt
    - stage: deploy
      script: cat test.txt
